# Generated by Django 4.1.5 on 2023-01-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_author_options_remove_author_birthday_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, unique=True, verbose_name='Название проекта')),
                ('link', models.CharField(max_length=512, verbose_name='Ссылка на репозиорий')),
                ('authors', models.ManyToManyField(to='mainapp.author')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Текст')),
                ('create_date', models.DateTimeField(verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(verbose_name='Статус активности')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
