# Generated by Django 4.1.5 on 2023-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_todo_author_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Признак обычного сотрудника'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Признак суперпользователя'),
        ),
    ]
