# Generated by Django 4.1.5 on 2023-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='birthday_year',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='author',
            name='user_name',
            field=models.CharField(default=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'), max_length=64, unique=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
    ]
